#!/usr/bin/env bash
# Puts `humanize-lint` on PATH so the skill can call the checker without knowing
# which install route placed it. Safe to re-run; it overwrites its own shim only.
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECKER="$SKILL_DIR/scripts/humanize_lint.py"
BIN_DIR="${HUMANIZE_BIN_DIR:-$HOME/.local/bin}"
SHIM="$BIN_DIR/humanize-lint"

if [ ! -f "$CHECKER" ]; then
  echo "error: checker not found at $CHECKER" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 not found. The checker needs Python 3.8 or newer." >&2
  exit 1
fi

mkdir -p "$BIN_DIR"
cat > "$SHIM" <<EOF
#!/usr/bin/env bash
# Generated by install-shim.sh. Points at the skill copy that created it.
exec python3 "$CHECKER" "\$@"
EOF
chmod +x "$SHIM"

echo "installed humanize-lint -> $CHECKER"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo
    echo "$BIN_DIR is not on your PATH. Add this to your shell profile:"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo "Until then, call the checker directly:"
    echo "  python3 $CHECKER draft.md"
    ;;
esac
